# The first server block will be the default server, it will answer all requests
# that dont belong to another server.

## * Main server block;
server:
    # * Webserver specifications;
    listen:                     # mandatory
        host: localhost   
        port: 8080
    server_name: example.com
    max_cbsize: 2000m
    max_conn: 1
    root: /www   # * Root definition
    index: pages/index.html
    http_methods: GET POST
    error_pages:   # * Error pages map;
        403: error/403.html
        400: error/400.html
        # 404: error/404.asf    # works with every type of file
        404: error/404.html
    cgi:   # * CGI extension exec. path map;
        .py: /usr/bin/python3
        # .php: /usr/bin/php
    # * Server routing;
    route /main:
        root: /www/pages
        redirect: /up
        index: favicon.ico
        dir_listing: off
        http_methods: GET POST 
    route /up:
        root: /www/uploads
        dir_listing: on
        http_methods: GET POST DELETE
        
    # * CGI routing;
    route /py:
        root: /cgi-bin/py
        index: index.py
        http_methods: GET POST DELETE
    route /php:
        root: /cgi-bin/php
        index: index.php
        http_methods: GET POST DELETE
    route /login:
        root: /cgi-bin/py/auth
        index: login.py
        http_methods: GET POST
    route /register:
        root: /cgi-bin/py/auth
        index: register.py
        http_methods: GET POST

server:
    listen:
        host: localhost
        port: 8081
    server_name: example2.com
    root: /
    dir_listing: on
    http_methods: GET
    index: xedni.html
    error_pages:
        400: error/400.html
    max_cbsize: 2000m
    max_conn: 5
    route /s:
        root: /srcs
        dir_listing: on
        http_methods: GET

# server:
#     listen:
#         host: localhost
#         port: 1234
#     server_name: example2.com
#     root: /
#     index: xedni.html
#     error_pages:
#         400: error/400.html
#     max_conn: 5
#     max_cbsize: 1m