# The first server block will be the default server, it will answer all requests
# that dont belong to another server.

server:
    listen:                     # mandatory
        host: localhost   
        port: 8080
    server_name: example.com
    root: /pages
    index: ind3x.html index.html
    http_methods: GET POST
    error_pages:
        404: error/404.html
        403: error/403.html
        400: error/400.html
    max_cbsize: 2000m              # to do: conversion and mapping
    max_conn: 10
    route /main:               # to do: HTTP redirect.
        root: /pages
        index: index.html       # default file to open if the request is the dir
        dir_listing: on         # 'on' or 'off'
        redirect: ola
        http_methods: GET
    route /uploads:
        dir_listing: on         
        http_methods: GET POST DELETE
    route /uploads_other:                  
        dir_listing: off       
        http_methods: GET POST

server:
    listen:
        host: localhost
        port: 2020
    server_name: example2.com
    root: /home
    index: xedni.html
    error_pages:
        400: error/400.html
    max_cbsize: 1m
    max_conn: 5
    route /srcs:
        root: srcs/conn/

server:
    listen:
        host: localhost
        port: 1234
    server_name: example2.com
    root: /home
    index: xedni.html
    error_pages:
        400: error/400.html
    max_cbsize: 1m
    max_conn: 5