# The first server block will be the default server, it will answer all requests
# that dont belong to another server.

## * Main server block;
server:
    # * Webserver specifications;
    listen:                     # mandatory
        host: localhost   
        port: 8080
    server_name: example.com
    max_cbsize: 2000m              # to do: conversion and mapping
    max_conn: 10
    # * Root definition
    root: /
    dir_listing: on
    http_methods: GET POST
    # * Error pages map;
    error_pages:
        403: error/403.html
        400: error/400.html
        # 404: error/404.asf    # works with every type of file
        404: error/404.html
    # * CGI extension exec. path map;
    cgi:
        .py: /usr/bin/python3
        # .php: /usr/bin/php
    # * Server routing;
    route /main:                # to do: HTTP redirect.
        root: /pages
        index: favicon.ico       # default file to open if the request is the dir
        dir_listing: off
        http_methods: GET POST
    route /ola:
        root: /srcs/conn  
        dir_listing: on
        http_methods: GET
        index: a.cpp Res.cpp Req1.cpp
    route /up:
        root: /uploads
        dir_listing: on
        http_methods: GET POST DELETE

    # * CGI routing;
    route /py:
        root: /cgi-bin/py
        index: index.py
        http_methods: GET POST DELETE
    route /php:
        root: /cgi-bin/php
        index: index.php
        http_methods: GET POST DELETE

server:
    listen:
        host: localhost
        port: 2020
    server_name: example2.com
    root: /
    dir_listing: on
    http_methods: GET
    index: xedni.html
    error_pages:
        400: error/400.html
    max_cbsize: 2000m
    max_conn: 5
    route /s:
        root: /srcs
        dir_listing: on
        http_methods: GET

server:
    listen:
        host: localhost
        port: 1234
    server_name: example2.com
    root: /home
    index: xedni.html
    error_pages:
        400: error/400.html
    max_cbsize: 1m
    max_conn: 5